from __future__ import annotations

from typing import Protocol

from app.models.domain import Content, Question, QuizAttempt, SessionSummary, Student, StudentProgress, Subtopic


class AuthRepositoryContract(Protocol):
    def find_student_by_email(self, email: str) -> Student | None: ...
    def create_student(self, name: str, email: str) -> Student: ...
    def get_student(self, student_id: int) -> Student | None: ...


class DiagnosticRepositoryContract(Protocol):
    def get_diagnostic_questions(self) -> list[Question]: ...
    def get_student(self, student_id: int) -> Student | None: ...
    def get_subtopic(self, subtopic_id: int) -> Subtopic: ...
    def save_student_level(self, student_id: int, subtopic_id: int, level: str, score: int) -> None: ...
    def complete_diagnostic(self, student_id: int) -> None: ...


class SchedulerRepositoryContract(Protocol):
    def get_student_progress(self, student_id: int) -> list[StudentProgress]: ...
    def get_subtopic(self, subtopic_id: int) -> Subtopic: ...


class ContentRepositoryContract(Protocol):
    def list_subtopics(self) -> list[Subtopic]: ...
    def get_student_level(self, student_id: int, subtopic_id: int) -> str: ...
    def get_content(self, subtopic_id: int, level: str) -> Content: ...
    def get_subtopic(self, subtopic_id: int) -> Subtopic: ...


class QuizRepositoryContract(Protocol):
    def get_progress(self, student_id: int, subtopic_id: int) -> StudentProgress: ...
    def get_manual_questions(self, subtopic_id: int) -> list[Question]: ...
    def create_personalized_questions(self, student_id: int, subtopic_id: int, level: str) -> list[Question]: ...
    def create_session(self, student_id: int, subtopic_id: int) -> SessionSummary: ...
    def get_subtopic_title(self, subtopic_id: int) -> str: ...
    def get_generated_questions(self, student_id: int, subtopic_id: int) -> list[Question]: ...


class ResultsRepositoryContract(Protocol):
    def get_session(self, session_id: int) -> SessionSummary: ...
    def get_question(self, question_id: int) -> Question: ...
    def add_attempt(self, attempt: QuizAttempt) -> QuizAttempt: ...
    def get_attempts(self, session_id: int) -> list[QuizAttempt]: ...
    def get_progress(self, student_id: int, subtopic_id: int) -> StudentProgress: ...
    def save_progress(self, progress: StudentProgress) -> None: ...
    def save_session(self, session: SessionSummary) -> None: ...
    def get_question_answers(self, session_id: int): ...


class ProgressRepositoryContract(Protocol):
    def get_progress_records(self, student_id: int) -> list[StudentProgress]: ...
    def get_subtopic(self, subtopic_id: int) -> Subtopic: ...
    def get_session_history(self, student_id: int, subtopic_id: int) -> list[SessionSummary]: ...


class BehaviourRepositoryContract(Protocol):
    def add_snapshot(self, log): ...
    def get_session(self, session_id: int) -> SessionSummary: ...
    def save_session(self, session: SessionSummary) -> None: ...
    def list_snapshots(self, session_id: int): ...
    def list_student_sessions(self, student_id: int) -> list[SessionSummary]: ...
    def get_subtopic(self, subtopic_id: int) -> Subtopic | None: ...
